aramark/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users
end

aramark/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

aramark/app/models/user.rb
class User < ApplicationRecord
end

aramark/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :null_session
end

aramark/app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :set_user, only: [:show]

  def index
    @users = User.all
  end

  def show
  end

  def new
    @user = User.new
  end

  def create
    p "params: #{params}"
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email)
  end

end

aramark/app/helpers/application_helper.rb
module ApplicationHelper
end

aramark/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Aramark</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <section class="main">
      <%= yield %>
    </section>
  </body>
</html>

aramark/app/views/users/_form.erb
<%= simple_form_for(@user) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :first_name %>
    <%= f.input :last_name %>
    <%= f.input :email %>
    <%= hidden_field_tag :custom_id %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

<script type="text/javascript">
  document.addEventListener("turbolinks:load", () => {
    var customId = localStorage.getItem('customId');

    console.log(customId)
  });
</script>

aramark/app/views/users/index.html.erb
<div class="custom-container">
  <table>
    <thead>
      <tr>
        <th>First Name</th>
        <th>Last Name</th>
        <th>Email</th>
      </tr>
    </thead>
    
    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= user.first_name %></td>
          <td><%= user.last_name %></td>
          <td><%= user.email %></td>
        </tr>
      <% end %>
    <tbody>
  </table>

  <br />
  <%= link_to 'New User', new_user_path %>
</div>

aramark/app/views/users/new.html.erb
<div class="custom-container">
  <h1>New User</h1>

  <%= render 'form' %>
</div>

<script type="text/javascript">
  const PERMITTED_DOMAIN = 'http://local.personal.com:3002';

  // Send a message to the parent
  window.parent.postMessage(JSON.stringify({ isReady: true }), "*");

  // Receive message from the parent
  window.addEventListener('message', function(e) {
    if (e.origin !== PERMITTED_DOMAIN) {
      return;
    }

    if (e.data) {
      console.log("Received message from parent", e.data);
      const { message, value } = JSON.parse(e.data);

      if (message === 'sendIds') {
        console.log("Ids", JSON.parse(value));

        localStorage.setItem('customId', value.id);
      }
    }
  });
</script>

aramark/app/views/users/show.html.erb
<div class="custom-container">
  <p>
    <strong>First Name: <strong>
    <%= @user.first_name %>
  </p>
  <p>
    <strong>Last Name: <strong>
    <%= @user.last_name %>
  </p>
  <p>
    <strong>Email: <strong>
    <%= @user.email %>
  </p>

  <%= link_to 'Back', users_path %>
</div>